sylius_resource:
    resources:
        mango_extended_channels_plugin.timezone_entity:
            driver: doctrine/orm
            classes:
                model: MangoSylius\ExtendedChannelsPlugin\Entity\TimezoneEntity
